name: 'coverage'
on:
    pull_request_target:
        branches:
            - master
            - main
jobs:
    coverage:
        permissions: write-all
        runs-on: ubuntu-latest
        with: 
            working-directory: ./data_structures/linkedlist
            test-script: npm test
            annotations: none
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
